config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/heroes', to: 'heroes#index'
  get '/heroes/:id', to: 'heroes#show', id: /\d+/, as: 'hero'

  get '/comics', to: 'comics#index'
  get '/comics/:id', to: 'comics#show', id: /\d+/, as: 'comic'

  get '/searchcharacter', to: 'heroes#search', as: 'searchcharacter'
  get '/searchcomic', to: 'comics#search', as: 'searchcomic'


  root to: 'heroes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character_comic.rb
# frozen_string_literal: true

class CharacterComic < ApplicationRecord
  belongs_to :hero
  belongs_to :comic
end

app/models/comic.rb
# frozen_string_literal: true

class Comic < ApplicationRecord
  has_many :character_comics
  has_many :heros, through: :character_comics, dependent: :destroy

  validates :title, presence: true
end

app/models/hero.rb
# frozen_string_literal: true

class Hero < ApplicationRecord
  belongs_to :planet

  has_many :character_comics
  has_many :comics, through: :character_comics, dependent: :destroy

  validates :name, presence: true
end

app/models/planet.rb
# frozen_string_literal: true

class Planet < ApplicationRecord
  has_many :heros

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comics_controller.rb
# frozen_string_literal: true

class ComicsController < ApplicationController
  def index
    @comics = Comic.all.order(:title).page(params[:page]).per(30)
  end

  def show
    @comic = Comic.find(params[:id])
  end

  def search
    @comics = Comic.where('title LIKE ?', "%#{params[:search_term]}%").order(:title).page(params[:page]).per(30)
  end
end

app/controllers/heroes_controller.rb
# frozen_string_literal: true

class HeroesController < ApplicationController
  def index
    @heroes = Hero.includes(:planet).order(:name).page(params[:page]).per(30)
  end

  def show
    @hero = Hero.includes(:planet).find(params[:id])
  end

  def search
    @heroes = Hero.where('name LIKE ?', "%#{params[:search_term]}%").order(:name).page(params[:page]).per(30)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/heroes_helper.rb
module HeroesHelper
end

app/views/comics/_search_form.html.erb
<%= form_with(url: searchcomic_path, local:true, method: "get") do %>
  <div class="field has-addons">
    <div class="control">
      <%= text_field_tag(:search_term, nil, class:'input', placeholder:'Comics by title') %>
    </div>
    <div class="control">
      <%= submit_tag("Search", class:"button is-info") %>
    </div>
  </div>
<% end %>

app/views/comics/index.html.erb
<%=render partial: 'comics/search_form'%>
<br>
<%=paginate @comics%>
<div class="columns is-multiline">
<%@comics.each do |comic|%>
  <div class="column is-one-third">
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure>
              <img src="<%=comic.thumbnail_path%>.<%=comic.thumbnail_extension%>" alt="<%=comic.title%>" width="100"/>
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-5"><%=link_to comic.title, comic%></p>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>
</div>
<%=paginate @comics%>

app/views/comics/search.html.erb
<%=render partial: 'comics/search_form'%>
<br>
<p class="subtitle is-7">
Found <%=pluralize(@comics.size, 'result')%>
for the search term "<%=params[:search_term] %>".
</p>
<%=paginate @comics%>
<div class="columns is-multiline">
<%@comics.each do |comic|%>
  <div class="column is-one-third">
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure>
              <img src="<%=comic.thumbnail_path%>.<%=comic.thumbnail_extension%>" alt="<%=comic.title%>" width="100"/>
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-5"><%=link_to comic.title, comic%></p>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>
</div>
<%=paginate @comics%>

app/views/comics/show.html.erb
<%=render partial: 'comics/search_form'%>
<br>
<div class="columns">
  <div class="card1">
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <figure>
            <img  src="<%=@comic.thumbnail_path%>.<%=@comic.thumbnail_extension%>" alt="<%=@comic.title%>" width="300" />
          </figure>
        </div>
        <div class="media-content">
          <p class="title is-4 has-text-danger"><%=@comic.title%></p>
          <p><%=@comic.description%></p>
          <br>
          <p>Pages: <%=@comic.page_count%></p>
        </div>
      </div>
    </div>
  </div>
</div>


<footer class="card-footer">
  <p class="card-footer-item">
  Characters:  <%=@comic.character_comics.count%>
</footer>

<div class="columns is-multiline">
  <div class="column is-one-third">
    <% if @comic.character_comics.empty?%>
      <p>No characters listed for <%= @comic.title %></p>
    <% else %>
      <ul>
        <% @comic.character_comics.each do |characterComic| %>
          <li>
            <%= link_to characterComic.hero.name, characterComic.hero%>
          </li>
        <%end%>
      </ul>
    <% end %>
  </div>
</div>

app/views/heroes/_hero.html.erb
<%=render partial: 'heroes/search_form'%>
<br>
<div class="columns">
  <div class="card1">
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <figure>
            <img src="<%=@hero.thumbnail_path%>.<%=@hero.thumbnail_extension%>" alt="<%=@hero.name%>" width="300"/>
          </figure>
        </div>
        <div class="media-content">
          <p class="title is-4 has-text-danger"><%=@hero.name%></p>
          <p class="title is-6">Home Planet: <%= @hero.planet.name %></p>
          <p class="title is-6">Archrival: <%= @hero.villain %></p>
          <p><%=@hero.description%></p>
        </div>
      </div>
    </div>
  </div>
</div>

<footer class="card-footer">
  <p class="card-footer-item">
  Comics: <%=@hero.character_comics.count%>
</footer>

<div class="columns is-multiline">
  <div class="column is-one-third">
    <% if @hero.character_comics.empty?%>
        <p>No comics listed for <%= @hero.name %></p>
    <% else %>
      <ul>
        <% @hero.character_comics.each do |characterComic| %>
          <li>
            <%= link_to characterComic.comic.title, characterComic.comic%>
          </li>
        <%end%>
      </ul>
    <% end %>
  </div>
</div>

app/views/heroes/_search_form.html.erb
<%= form_with(url: searchcharacter_path, local:true, method: "get") do %>
  <div class="field has-addons">
    <div class="control">
      <%= text_field_tag(:search_term, nil, class:'input', placeholder:'Characters by name') %>
    </div>
    <div class="control">
      <%= submit_tag("Search", class:"button is-info") %>
    </div>
  </div>
<% end %>

app/views/heroes/index.html.erb
<%=render partial: 'heroes/search_form'%>
<br>
<%=paginate @heroes%>
<div class="columns is-multiline">
<%@heroes.each do |hero|%>
  <div class="column is-one-third">
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure >
              <img src="<%=hero.thumbnail_path%>.<%=hero.thumbnail_extension%>" alt="<%=hero.name%>" width="100"/>
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-4"><%=link_to hero.name, hero%></p>
            <p> <%=hero.description%></p>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>
</div>
<%=paginate @heroes%>

app/views/heroes/search.html.erb
<%=render partial: 'heroes/search_form'%>
<br>
<p class="subtitle is-7">
Found <%=pluralize(@heroes.size, 'result')%>
for the search term "<%=params[:search_term] %>".
</p>
<%=paginate @heroes%>
<div class="columns is-multiline">
<%@heroes.each do |hero|%>
  <div class="column is-one-third">
    <div class="card">
      <div class="card-content">
        <div class="media">
          <div class="media-left">
            <figure >
              <img src="<%=hero.thumbnail_path%>.<%=hero.thumbnail_extension%>" alt="<%=hero.name%>" width="100"/>
            </figure>
          </div>
          <div class="media-content">
            <p class="title is-4"><%=link_to hero.name, hero%></p>
            <p> <%=hero.description%></p>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>
</div>
<%=paginate @heroes%>

app/views/heroes/show.html.erb
<%=render  partial: 'hero',
            object: @hero %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marvel on Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
  </head>


  <body>
  <section class="section">
    <div class="container">
      <header>
        <h1 class="title is-1"><%= link_to 'Marvel on Rails', root_path %></h1>
        <h2><%= link_to 'Characters', root_path %> | <%= link_to 'Comics', comics_path %> | About </h2>
      </header>
      <div class="field">
        <div class="control">
        <div class="select is-info">
          <%= select_tag(:search_id, options_for_select([['Search category', 1], ['Character', 2], ['Comic', 3]]),  {:class => "select is-info"})  %>
        </div>
        </div>
      </div>
    <%= yield %>
    </div>
  </section>
  </body>
</html>